# Generated by Django 4.1.6 on 2023-02-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='estado',
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('categoria', models.ManyToManyField(to='endpoints.categoria')),
            ],
        ),
    ]
