# Generated by Django 4.1.6 on 2023-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_remove_categoria_estado_alter_plato_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='plato',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='plato',
            name='Categoria',
            field=models.ManyToManyField(to='endpoints.categoriap'),
        ),
    ]
