# Generated by Django 4.1.6 on 2023-02-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_categoriap_alter_plato_url_plato_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='categoria',
        ),
        migrations.AddField(
            model_name='plato',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoints.categoriap'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoints.categoria'),
        ),
    ]
