# Generated by Django 4.1.6 on 2023-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_remove_plato_categoria_remove_restaurante_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='plato',
            field=models.ManyToManyField(to='endpoints.plato'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
