# Generated by Django 4.1.6 on 2023-03-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0008_usuario_cliente_usuario_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='plato',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='plato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoints.plato'),
        ),
    ]
